seed: 42

data:
  train_split: 0.8
  random_state: 42
  batch_size: 1    
  num_workers: 0
  input_size: 224

model:
  name: resnet18
  pretrained: False
  feature_extract: False
  model_checkpoint: "checkpoint.pt"

training:
  optimizer: sgd
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.0001
  scheduler: none
  step_size: 10
  gamma: 0.1
  epochs: 5             

augmentation:
  random_flip: False
  color_jitter: False
  cutmix: False

early_stopping:
  patience: 7
  verbose: True
  delta: 0.0
  es_path: './checkpoint.pt'
  
# adversarial patch attack
patch_checkpoint: "untargeted_adv_patch.pt"
label_encoder_path: "label_encoder.pkl"
data_root: "/kaggle/input/the-simpsons-characters-dataset/simpsons_dataset/simpsons_dataset"

# NES untargeted attack
patch_size: 75
noise_samples: 20
sigma: 0.1
max_queries: 20000

# Occlusion / Grad-CAM
occlusion_size: 30
occlusion_stride: 15
gradcam_target_layer: "layer4"
save_vis_dir: "vis_results"
