# config.yaml
seed: 42

data:
  train_split: 0.8
  random_state: 42
  batch_size: 32
  num_workers: 0
  input_size: 224

model:
  name: resnet18     # resnet18, resnet152 
  pretrained: true
  feature_extract: false
  feature_extract: false

training:
  optimizer: sgd
  lr: 0.001
  momentum: 0.9
  weight_decay: 1e-4
  scheduler: none    # none, step, cosine, onecycle
  step_size: 10
  gamma: 0.1
  epochs: 2

augmentation:
  random_flip: true
  color_jitter: false
  cutmix: false