# config.yaml
seed: 42

data:
  train_split: 0.8
  random_state: 42
  batch_size: 32
  num_workers: 0
  input_size: 224

model:
  name: resnet18     # resnet18, resnet152 
  pretrained: false
  feature_extract: false

training:
  optimizer: sgd
  lr: 0.001
  momentum: 0.9
  weight_decay: !!float 1e-4
  scheduler: none    # none, step, cosine, onecycle
  step_size: 10
  gamma: 0.1
  epochs: 30

augmentation:
  random_flip: false
  color_jitter: false
  cutmix: false

early_stopping:
  patience: 7          # How long to wait after last time validation loss improved.
  verbose: true        # If True, prints a message for each validation loss improvement.
  delta: 0.0           # Minimum change in the monitored quantity to qualify as an improvement.
  es_path: "./checkpoint.pt"  # Path for the checkpoint to be saved to.
